### ISSUE TITLE
[Suggestion] Make loadout stuffs less hardcode

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [PiMoNFeeD/csso-src#11]
has the tittle suggests making the loadout less hardcode (editable through a txt file), would allow server operators/mod makers add new stuffs to the mod without the need of re compiling the binaries

**Comment by PiMoNFeeD** [comment]
well first there's a separate repository for suggestions, second - its impossible because its tied with console commands and their values, plus it will require a lot of work on buymenu
