### ISSUE TITLE
[Suggestion] Backport csgo graphical features

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [PiMoNFeeD/csso-src#12]
I don't know if this would be really out of scope of the mod, but having some of he csgo shaders/effects (ex: csm, character shader, ect) here would make some maps looks nice and the backporting process of some maps would be less tedious

**Comment by PiMoNFeeD** [comment]
csm requires an extremely huge amount of work which is nearly impossible to make (if you're talking about csgo csm and not some third-party implementation of it) and shaders just cant be worked with currently cuz shader compiler crashes halfway through the compilation

and again there's a separate repository for suggestions -> https://github.com/PiMoNFeeD/csso-tracker
